import React, { useState, useEffect } from 'react';
import { Download, ArrowLeft, CheckCircle2 } from 'lucide-react';
import { jsPDF } from "jspdf";
import { ProcessingResult, ResultMode } from '../types';

interface ResultDisplayProps {
  result: ProcessingResult;
  onReset: () => void;
  sourceFileName: string;
  isStreaming: boolean;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ result, onReset, sourceFileName, isStreaming }) => {
  const [showNotification, setShowNotification] = useState(false);

  useEffect(() => {
    if (!isStreaming && result.text.length > 0) {
      setShowNotification(true);
      const timer = setTimeout(() => setShowNotification(false), 8000);
      return () => clearTimeout(timer);
    }
  }, [isStreaming]);

  const handleDownload = () => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxLineWidth = pageWidth - (margin * 2);
    
    const resetContentStyle = () => {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(0, 0, 0);
    };

    const addFooter = () => {
      doc.setFont("helvetica", "italic");
      doc.setFontSize(9);
      doc.setTextColor(128, 128, 128);
      doc.text("A Product of UniSpace", pageWidth / 2, pageHeight - 10, { align: "center" });
      resetContentStyle();
    };

    let title = 'Document';
    switch (result.mode) {
      case ResultMode.SOLVE: title = 'Exam Solutions'; break;
      case ResultMode.REVIEW: title = 'FlashCard Doc'; break;
      case ResultMode.SUMMARY: title = 'Document Summary'; break;
    }
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(7, 188, 12); // Using primary color #07bc0c
    doc.text(title, margin, 20);
    
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated by UniSpace AI on ${new Date().toLocaleString()}`, margin, 27);
    
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, 32, pageWidth - margin, 32);
    addFooter();
    resetContentStyle();

    let cursorY = 40;
    const lineHeight = 6;

    const printLine = (lineSegments: { text: string, width: number, isBold: boolean }[]) => {
      let currentX = margin;
      lineSegments.forEach(seg => {
        doc.setFont("helvetica", seg.isBold ? "bold" : "normal");
        doc.text(seg.text, currentX, cursorY);
        currentX += seg.width;
      });
    };

    const paragraphs = result.text.split('\n');
    paragraphs.forEach(paragraph => {
      if (cursorY > pageHeight - margin - 15) { 
        doc.addPage();
        addFooter();
        cursorY = margin;
      }
      const segments = paragraph.split(/\*\*(.*?)\*\*/g);
      let currentLine: { text: string, width: number, isBold: boolean }[] = [];
      let currentLineWidth = 0;

      segments.forEach((segment, index) => {
        const isBold = index % 2 === 1;
        const words = segment.split(/(\s+)/);
        words.forEach(word => {
          if (!word) return;
          doc.setFont("helvetica", isBold ? "bold" : "normal");
          const wordWidth = doc.getTextWidth(word);
          if (currentLineWidth + wordWidth > maxLineWidth) {
            printLine(currentLine);
            currentLine = [];
            currentLineWidth = 0;
            cursorY += lineHeight;
            if (cursorY > pageHeight - margin - 15) {
              doc.addPage();
              addFooter();
              cursorY = margin;
            }
          }
          currentLine.push({ text: word, width: wordWidth, isBold });
          currentLineWidth += wordWidth;
        });
      });
      if (currentLine.length > 0) {
        printLine(currentLine);
        cursorY += lineHeight;
      } else {
        cursorY += lineHeight / 2; 
      }
    });

    const cleanName = sourceFileName.replace(/\.[^/.]+$/, "");
    doc.save(`${cleanName}_UniSpace_AI.pdf`);
  };

  const isReviewMode = result.mode === ResultMode.REVIEW;
  const isSummaryMode = result.mode === ResultMode.SUMMARY;
  const completionMessage = isReviewMode ? "FlashCard Doc Ready!" : isSummaryMode ? "Summary Complete!" : "Solutions Ready!";

  return (
    <div className="relative flex flex-col space-y-4">
      {showNotification && (
        <div className="flex items-center justify-between bg-primary text-white px-6 py-3 rounded-xl shadow-lg animate-fade-in z-20">
          <div className="flex items-center space-x-3">
            <CheckCircle2 className="w-5 h-5 text-white" />
            <span className="font-medium text-sm md:text-base">{completionMessage}</span>
          </div>
          <button onClick={() => setShowNotification(false)} className="text-white/80 hover:text-white text-sm font-bold ml-4">
            DISMISS
          </button>
        </div>
      )}

      <div className={`bg-white dark:bg-gray-800 rounded-2xl shadow-lg border border-gray-200 dark:border-gray-700 overflow-hidden flex flex-col max-h-[800px] animate-unfold-up transition-colors`}>
        <div className={`px-6 py-4 flex justify-between items-center border-b border-gray-100 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900/50`}>
          <div className="flex items-center space-x-4">
            <button onClick={onReset} className="p-2 rounded-full hover:bg-white dark:hover:bg-gray-700 transition-colors text-gray-600 dark:text-gray-400">
              <ArrowLeft className="w-5 h-5" />
            </button>
            <div>
              <h2 className="text-xl font-bold text-gray-900 dark:text-white">
                {isReviewMode ? 'FlashCard Doc' : isSummaryMode ? 'Summary' : 'Exam Solutions'}
              </h2>
              <p className="text-sm text-gray-500 dark:text-gray-400">
                {isStreaming ? 'AI is thinking...' : 'Ready to download'}
              </p>
            </div>
          </div>
          <button 
            onClick={handleDownload}
            disabled={isStreaming}
            className="flex items-center space-x-2 px-4 py-2 rounded-lg text-sm font-semibold transition-all shadow-sm text-white bg-primary hover:bg-primary-dark disabled:opacity-50"
          >
            <Download className="w-4 h-4" />
            <span>Download PDF</span>
          </button>
        </div>

        <div className="p-8 overflow-y-auto custom-scrollbar bg-white dark:bg-gray-800">
          <div className="prose prose-slate dark:prose-invert max-w-none text-gray-800 dark:text-gray-200 whitespace-pre-wrap leading-relaxed">
            {result.text}
            {isStreaming && <span className="inline-block w-2 h-4 bg-primary animate-pulse ml-1"></span>}
          </div>
        </div>
      </div>
    </div>
  );
};

export default ResultDisplay;