import React from 'react';
import { Download, ArrowLeft } from 'lucide-react';
import { jsPDF } from "jspdf";
import { ProcessingResult, ResultMode } from '../types';

interface ResultDisplayProps {
  result: ProcessingResult;
  onReset: () => void;
  sourceFileName: string;
}

const ResultDisplay: React.FC<ResultDisplayProps> = ({ result, onReset, sourceFileName }) => {
  
  const handleDownload = () => {
    // Create new PDF document
    const doc = new jsPDF();
    
    // Page configuration
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxLineWidth = pageWidth - (margin * 2);
    
    // -- Header Section --
    let title = 'Document';
    switch (result.mode) {
      case ResultMode.SOLVE: title = 'Exam Solutions'; break;
      case ResultMode.REVIEW: title = 'Quick Review Flashcards'; break;
      case ResultMode.SUMMARY: title = 'Document Summary'; break;
    }
    
    // Title Font
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.setTextColor(40, 40, 40);
    doc.text(title, margin, 20);
    
    // Subtitle / Date
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const dateStr = new Date().toLocaleString();
    
    // Updated Footer Text
    doc.text(`Generated by AI Exam Solver_UniSpace on ${dateStr}`, margin, 27);
    
    // Draw a divider line
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, 32, pageWidth - margin, 32);

    // -- Content Section --
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(0, 0, 0);

    let cursorY = 40; // Start position below header
    const lineHeight = 6;

    // Helper to print a constructed line with mixed styles
    const printLine = (lineSegments: { text: string, width: number, isBold: boolean }[]) => {
      let currentX = margin;
      lineSegments.forEach(seg => {
        doc.setFont("helvetica", seg.isBold ? "bold" : "normal");
        doc.text(seg.text, currentX, cursorY);
        currentX += seg.width;
      });
    };

    // Text Parser and Renderer
    // This splits text by newlines, then by bold markers (**), and renders wrapped lines
    const paragraphs = result.text.split('\n');

    paragraphs.forEach(paragraph => {
      // Check for page break at start of paragraph
      if (cursorY > pageHeight - margin) {
        doc.addPage();
        cursorY = margin;
      }

      // 1. Split by Markdown Bold markers: **text**
      // The regex capturing group (.*?) ensures the bold text is included in the split array at odd indices.
      const segments = paragraph.split(/\*\*(.*?)\*\*/g);

      let currentLine: { text: string, width: number, isBold: boolean }[] = [];
      let currentLineWidth = 0;

      segments.forEach((segment, index) => {
        // Even indices are normal text, Odd indices are bold text (captured by regex)
        const isBold = index % 2 === 1;

        // 2. Split segment into words to handle wrapping
        // We use split with capturing group for whitespace to preserve spaces between words
        const words = segment.split(/(\s+)/);

        words.forEach(word => {
          if (!word) return;

          doc.setFont("helvetica", isBold ? "bold" : "normal");
          const wordWidth = doc.getTextWidth(word);

          // If adding this word exceeds max width, print current line and start new one
          if (currentLineWidth + wordWidth > maxLineWidth) {
            // Print the filled line
            printLine(currentLine);
            
            // Reset for next line
            currentLine = [];
            currentLineWidth = 0;
            cursorY += lineHeight;

            // Check page break
            if (cursorY > pageHeight - margin) {
              doc.addPage();
              cursorY = margin;
            }

            // If the word causing the wrap is just a space, skip it at the start of new line
            if (/^\s+$/.test(word)) return;
          }

          // Add word to buffer
          currentLine.push({ text: word, width: wordWidth, isBold });
          currentLineWidth += wordWidth;
        });
      });

      // Print any remaining text in the buffer for this paragraph
      if (currentLine.length > 0) {
        printLine(currentLine);
        cursorY += lineHeight;
      } else {
        // If paragraph was empty (just a newline in source), add a small gap
        cursorY += lineHeight / 2; 
      }
    });

    // Save the PDF with specific naming convention: [Title]_UniSpace.pdf
    const cleanName = sourceFileName.replace(/\.[^/.]+$/, "");
    const filename = `${cleanName}_UniSpace.pdf`;
    doc.save(filename);
  };

  const isReviewMode = result.mode === ResultMode.REVIEW;
  const isSummaryMode = result.mode === ResultMode.SUMMARY;

  let headerColorClass = 'bg-green-50 border-green-100';
  let titleColorClass = 'text-green-900';
  let btnColorClass = 'bg-green-600 hover:bg-green-700';

  if (isReviewMode) {
    headerColorClass = 'bg-indigo-50 border-indigo-100';
    titleColorClass = 'text-indigo-900';
    btnColorClass = 'bg-indigo-600 hover:bg-indigo-700';
  } else if (isSummaryMode) {
    headerColorClass = 'bg-blue-50 border-blue-100';
    titleColorClass = 'text-blue-900';
    btnColorClass = 'bg-blue-600 hover:bg-blue-700';
  }

  return (
    <div className="bg-white rounded-2xl shadow-lg border border-gray-200 overflow-hidden flex flex-col max-h-[800px]">
      {/* Header */}
      <div className={`px-6 py-4 flex justify-between items-center border-b ${headerColorClass}`}>
        <div className="flex items-center space-x-4">
          <button 
            onClick={onReset}
            className="p-2 rounded-full hover:bg-white/50 transition-colors text-gray-600"
            title="Back to Upload"
          >
            <ArrowLeft className="w-5 h-5" />
          </button>
          <div>
            <h2 className={`text-xl font-bold ${titleColorClass}`}>
              {isReviewMode ? 'Quick Review Flashcards' : isSummaryMode ? 'Document Summary' : 'Exam Solutions'}
            </h2>
            <p className="text-sm text-gray-500">Generated from your uploaded materials</p>
          </div>
        </div>
        <button 
          onClick={handleDownload}
          className={`flex items-center space-x-2 px-4 py-2 rounded-lg text-sm font-semibold transition-colors shadow-sm text-white ${btnColorClass}`}
        >
          <Download className="w-4 h-4" />
          <span>Download PDF</span>
        </button>
      </div>

      {/* Content Area */}
      <div className="p-8 overflow-y-auto custom-scrollbar bg-white">
        {isReviewMode ? (
          /* Q&A Style Format */
          <div className="font-mono text-sm space-y-4 text-gray-800 whitespace-pre-wrap">
             {result.text}
          </div>
        ) : (
          /* Detailed Solution & Summary Format */
          <div className="prose prose-slate max-w-none text-gray-800 whitespace-pre-wrap">
            {result.text}
          </div>
        )}
      </div>
    </div>
  );
};

export default ResultDisplay;